repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: end-of-file-fixer
    files: \.(py|sh|rst|yml|yaml)$
  - id: mixed-line-ending
  - id: trailing-whitespace
    files: \.(py|sh|rst|yml|yaml)$
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pappasam/toml-sort
  rev: v0.20.1
  hooks:
  - id: toml-sort
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.2.0
  hooks:
  - id: setup-cfg-fmt
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.11.4
  hooks:
  - id: isort
- repo: https://github.com/csachs/pyproject-flake8
  rev: v6.0.0.post1
  hooks:
  - id: pyproject-flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    additional_dependencies:
    - types-PyAutoGUI
    - git+https://github.com/python-qt-tools/PyQt6-stubs
    files: ^rendakun/
    args: [--strict]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint
    args: [--disable=MD013]
